#!/bin/bash
#SBATCH --job-name=sassena
#SBATCH --nodes=1             # run all processes on a single node
#SBATCH --nodes=1             # run all processes on a single node
#SBATCH --ntasks-per-node=24  # number of MPI tasks (i.e. processes)
#SBATCH --cpus-per-task=1     # number of cores per MPI task (=OMP_NUM_THREADS)
#SBATCH --mem-per-cpu=2G      # 96GB RAM per node, 2 sockets * 12 cores * 2 threads
#SBATCH --output=out_%j.log   # Jobnumber mit dem Output
echo "Date              = $(date)"
echo "Hostname          = $(hostname -s)"
echo "Working Directory = $(pwd)"
echo ""
echo "Number of Nodes Allocated      = $SLURM_JOB_NUM_NODES"
echo "Number of Tasks Allocated      = $SLURM_NTASKS"
echo "Number of Cores/Task Allocated = $SLURM_CPUS_PER_TASK"
echo ""
module purge
module load boost hdf5 compiler mpi mkl
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
mpiexec -n $SLURM_NTASKS /data/data/amajumda/sass_paper/sassena_Glab/sassena/compile_boxcut_img/sassena --config scatter.xml


